server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dmc?useUnicode=true&useSSL=false
    username: root
    password: 12345678

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


---
spring:
  profiles:
    active: dev # For deployment in dev

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data.mongodb: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    org.apache: INFO
    org.mongodb.driver: INFO
    com.dmc: DEBUG

---
spring:
  profiles: test # For deployment in test