server:
  port: 9003


spring:
  datasource:
    url: jdbc:mysql://121.41.119.158:3306/dmc?useUnicode=true&useSSL=false
    username: dmc
    password: dmc123456

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-configuration.xml


---
spring:
  profiles:
    active: dev # For deployment in dev

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data.mongodb: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG


    org.apache: INFO
    org.mongodb.driver: INFO
    com.dmc: DEBUG

---
spring:
  profiles: test # For deployment in test